import type { Product, ProductCategory, ProductTag } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Organic Fertilizer - Premium Blend",
    category: "Fertilizers",
    description:
      "Premium organic fertilizer blend for all crops. Enhances soil health and promotes sustainable farming practices.",
    price: 1200,
    rating: 4.8,
    reviewCount: 156,
    image: "/organic-fertilizer-mix.png",
    tags: ["organic", "sustainable"],
    label: "Best Seller",
    inStock: true,
  },
  {
    id: "2",
    name: "Solar Water Pump System",
    category: "Irrigation Systems",
    description:
      "Solar-powered water pump system with battery backup. Ideal for remote farms without reliable electricity.",
    price: 22500,
    originalPrice: 25000,
    rating: 4.7,
    reviewCount: 48,
    image: "/placeholder-t226q.png",
    tags: ["sustainable", "water-saving"],
    label: "10% Off",
    inStock: true,
    stockCount: 5,
  },
  {
    id: "3",
    name: "Neem Oil Organic Pesticide",
    category: "Pesticides",
    description: "100% natural neem oil pesticide. Safe for organic farming and effective against most common pests.",
    price: 850,
    rating: 4.9,
    reviewCount: 212,
    image: "/placeholder-t74io.png",
    tags: ["organic", "natural"],
    label: "Best Seller",
    inStock: true,
  },
  {
    id: "4",
    name: "Drip Irrigation Kit - Small Farm",
    category: "Irrigation Systems",
    description: "Complete drip irrigation system for up to 1 acre. Water-efficient and easy to install.",
    price: 8500,
    rating: 4.7,
    reviewCount: 89,
    image: "/drip-irrigation.png",
    tags: ["water-saving", "sustainable"],
    inStock: true,
  },
  {
    id: "5",
    name: "Handheld Soil Tester Kit",
    category: "Tools & Equipment",
    description: "Test soil pH, moisture, and nutrient levels instantly. Battery-operated with digital display.",
    price: 2800,
    originalPrice: 3200,
    rating: 4.5,
    reviewCount: 60,
    image: "/placeholder-rlsxe.png",
    tags: ["digital"],
    label: "15% Off",
    inStock: true,
  },
  {
    id: "6",
    name: "High-Yield Tomato Seeds (Pack of 100)",
    category: "Seeds",
    description: "Disease-resistant, high-yield tomato variety suitable for various climates.",
    price: 450,
    rating: 4.6,
    reviewCount: 78,
    image: "/tomato-seeds.png",
    tags: ["high-yield"],
    inStock: true,
  },
  {
    id: "7",
    name: "Protective Farming Gloves",
    category: "Safety Equipment",
    description: "Durable, puncture-resistant gloves for farm work. Comfortable fit with excellent grip.",
    price: 650,
    rating: 4.4,
    reviewCount: 42,
    image: "/placeholder-9c5g9.png",
    tags: [],
    inStock: true,
  },
  {
    id: "8",
    name: "Smart Irrigation Controller",
    category: "Irrigation Systems",
    description: "WiFi-enabled irrigation controller. Schedule watering based on weather forecasts and soil moisture.",
    price: 4500,
    rating: 4.8,
    reviewCount: 35,
    image: "/placeholder-6gs8d.png",
    tags: ["digital", "water-saving"],
    label: "New",
    inStock: true,
  },
]

export const categories: ProductCategory[] = [
  "All Categories",
  "Fertilizers",
  "Seeds",
  "Pesticides",
  "Irrigation Systems",
  "Tools & Equipment",
  "Safety Equipment",
]

export const tags: ProductTag[] = ["organic", "sustainable", "high-yield", "water-saving", "natural", "digital"]

export const sortOptions = [
  { value: "featured", label: "Featured" },
  { value: "price-low-high", label: "Price: Low to High" },
  { value: "price-high-low", label: "Price: High to Low" },
  { value: "rating", label: "Highest Rated" },
  { value: "newest", label: "Newest" },
]
